### ISSUE TITLE
[Request] Button to retry download

### ISSUE THREAD

**Issue by AldebaraanMKII** [FaultierSP/civitaiapiclient#6]
For some unknown reason my internet disconnected during download and i got a error and had to start over (loading metadata again). It would be good if there was a button to retry the download from where it stopped without needing to start again.

How to replicate this: Disconnect your internet during a download.

**Comment by FaultierSP** [comment]
I don't really know about that, tbh.

The app already doesn't download images over, it just skips them and gets only new ones.

As for the metadata, I do not have much trust in the consistency of the API response. The way it works is like this: you get data for, say, 200 images and a cursor that points to the next batch. Let's say your cat runs over your router and kills connection for 5 minutes. In this time user can upload new pictures or take down old ones, so your cursor pointer and batches are screwed up. You would need to start over again anyways, because starting all over would be faster than checking the data in memory.

Feel free to share your thoughts on this though.

**Comment by AldebaraanMKII** [comment]
If you think it is best that way i will close this then.
Thanks for all the hard work!
