### ISSUE TITLE
The program finds fewer files than indicated on the website

### ISSUE THREAD

**Issue by VanTuz5** [FaultierSP/civitaiapiclient#8]
As an example, the author's page (LegioN70) indicates that he has 2491 images (at the moment), but the program finds only 2447. It's a small thing, but annoying.

**Comment by FaultierSP** [comment]
I wish you knew how much time I spent trying to figure it out. :)

The honest answer is, I don't know what's happening. But based on the behavior of the app as it collects data, I would say that API simply doesn't provide all the images. It would be one of many bugs and undocumented behavior of the API. But I think the Civitai team is stressed out right now, because they don't event respond or engage with small hobby devs like myself.

**Comment by VanTuz5** [comment]
In principle, that's what I thought, but I decided to check if this bug can be fixed somehow. But since the problem is on the side of civitai, we can only wait until they fix everything there. If they fix it.
